import iconStar from '@/../public/assets/svg/16/icon Star.svg';

import arrowLeft from '@/../public/assets/svg/24/arrow-left.svg';
// import arrowRight from '@/../public/assets/svg/24/arrow-right.svg';
import arrowRightTail from '@/../public/assets/svg/24/arrow-right 24х24.svg';
import calendar from '@/../public/assets/svg/24/calendar.svg';
import call2 from '@/../public/assets/svg/24/call-2.svg';
import call21 from '@/../public/assets/svg/24/call-2-1.svg';
import check from '@/../public/assets/svg/24/check.svg';
import graph from '@/../public/assets/svg/24/graph.svg';
import group from '@/../public/assets/svg/24/group.svg';
import pencil from '@/../public/assets/svg/24/pencil.svg';
import plus from '@/../public/assets/svg/24/plus.svg';
// import send from '@/../public/assets/svg/24/send-24х24.svg';
import settings from '@/../public/assets/svg/24/settings.svg';
import wifi from '@/../public/assets/svg/24/wifi.svg';

import likeHeart from '@/../public/assets/svg/24-variants/like-heart.svg';
import likeHeartActive from '@/../public/assets/svg/24-variants/like-heart-active.svg';

import info from '@/../public/assets/svg/28/info.svg';
import logOut from '@/../public/assets/svg/28/log-out.svg';

import bookmark from '@/../public/assets/svg/28-variants/bookmark.svg';
import bookmarkActive from '@/../public/assets/svg/28-variants/bookmark-active.svg';
import lock from '@/../public/assets/svg/28-variants/lock.svg';
import lockActive from '@/../public/assets/svg/28-variants/lock-active.svg';
import moreHorizontal from '@/../public/assets/svg/28-variants/more-horizontal.svg';
import moreVertical from '@/../public/assets/svg/28-variants/more-vertical.svg';
import notification from '@/../public/assets/svg/28-variants/notification.svg';
import notificationActive from '@/../public/assets/svg/28-variants/notification-active.svg';

import arrowDown from '@/../public/assets/svg/32/arrow-down.svg';
import arrowRight from '@/../public/assets/svg/32/arrow-right-32х32.svg';
import arrowUp from '@/../public/assets/svg/32/arrow-up.svg';
import aspect from '@/../public/assets/svg/32/aspect.svg';
import bookSaved from '@/../public/assets/svg/32/book-saved.svg';
import buildings2 from '@/../public/assets/svg/32/buildings-2.svg';
import camera from '@/../public/assets/svg/32/camera.svg';
import car from '@/../public/assets/svg/32/car.svg';
import clock from '@/../public/assets/svg/32/clock.svg';
import closeCircle from '@/../public/assets/svg/32/close-circle.svg';
import deleteBin from '@/../public/assets/svg/32/delete-bin.svg';
import hashtag from '@/../public/assets/svg/32/hashtag.svg';
import location from '@/../public/assets/svg/32/location.svg';
import map from '@/../public/assets/svg/32/map.svg';
import menuBoard from '@/../public/assets/svg/32/menu-board.svg';
import navigation from '@/../public/assets/svg/32/Navigation.svg';
import note2 from '@/../public/assets/svg/32/note-2.svg';
import people from '@/../public/assets/svg/32/people.svg';
import profile2user from '@/../public/assets/svg/32/profile-2user.svg';
import restaurantTable from '@/../public/assets/svg/32/Restaurant-table.svg';
import routing2 from '@/../public/assets/svg/32/routing-2.svg';
import searchNormal from '@/../public/assets/svg/32/search-normal.svg';
import securityUser from '@/../public/assets/svg/32/security-user.svg';
import send from '@/../public/assets/svg/32/send-32х32.svg';
import share from '@/../public/assets/svg/32/share.svg';
import share2 from '@/../public/assets/svg/32/share-2.svg';
import smsTracking from '@/../public/assets/svg/32/sms-tracking.svg';
import squares from '@/../public/assets/svg/32/squares.svg';
import textalignJustifycenter from '@/../public/assets/svg/32/textalign-justifycenter.svg';
import timerPause from '@/../public/assets/svg/32/timer-pause.svg';
import trade from '@/../public/assets/svg/32/trade.svg';
import verify from '@/../public/assets/svg/32/verify.svg';
import view360 from '@/../public/assets/svg/32/view-360.svg';

import account1 from '@/../public/assets/svg/32-variants/account-1.svg';
import account2 from '@/../public/assets/svg/32-variants/account-2.svg';
import cart from '@/../public/assets/svg/32-variants/cart.svg';
import cartNumbers from '@/../public/assets/svg/32-variants/cart-numbers.svg';
import like from '@/../public/assets/svg/32-variants/like.svg';
import likeDislike from '@/../public/assets/svg/32-variants/like-dislike.svg';
import settingsEq from '@/../public/assets/svg/32-variants/settings-eq.svg';
import settingsEqActive from '@/../public/assets/svg/32-variants/settings-eq-active.svg';
import shoppingBag from '@/../public/assets/svg/32-variants/shopping-bag.svg';
import shoppingBagActive from '@/../public/assets/svg/32-variants/shopping-bag-active.svg';
import viewFilterOff from '@/../public/assets/svg/32-variants/view-filter-off.svg';
import viewFilterOn from '@/../public/assets/svg/32-variants/view-filter-on.svg';

import locationAccent from '@/../public/assets/svg/40-variants/location-accent.svg';
import locationAccentNumbers from '@/../public/assets/svg/40-variants/location-accent-numbers.svg';

import mistake from '@/../public/assets/svg/160-variants/mistake.svg';
import successfully from '@/../public/assets/svg/160-variants/successfully.svg';

import Image from 'next/image';

export const IconStar = () => <Image src={iconStar} alt="iconStar" />;
export const ArrowLeft = () => <Image src={arrowLeft} alt="arrowLeft" />;
// export const ArrowRight = () => <Image src={arrowRight} alt="arrowRight" />;
export const ArrowRightTail = () => <Image src={arrowRightTail} alt="arrowRightTail" />;
export const Calendar = () => <Image src={calendar} alt="calendar" />;
export const Call2 = () => <Image src={call2} alt="call2" />;
export const Call21 = () => <Image src={call21} alt="call21" />;
export const Check = () => <Image src={check} alt="check" />;
export const Graph = () => <Image src={graph} alt="graph" />;
export const Group = () => <Image src={group} alt="group" />;
export const Pencil = () => <Image src={pencil} alt="pencil" />;
export const Plus = () => <Image src={plus} alt="plus" />;
export const Settings = () => <Image src={settings} alt="settings" />;
export const Wifi = () => <Image src={wifi} alt="wifi" />;
export const LikeHeart = () => <Image src={likeHeart} alt="likeHeart" />;
export const LikeHeartActive = () => <Image src={likeHeartActive} alt="likeHeartActive" />;
export const Info = () => <Image src={info} alt="info" />;
export const LogOut = () => <Image src={logOut} alt="logOut" />;
export const Bookmark = () => <Image src={bookmark} alt="bookmark" />;
export const BookmarkActive = () => <Image src={bookmarkActive} alt="bookmarkActive" />;
export const Lock = () => <Image src={lock} alt="lock" />;
export const LockActive = () => <Image src={lockActive} alt="lockActive" />;
export const MoreHorizontal = () => <Image src={moreHorizontal} alt="moreHorizontal" />;
export const MoreVertical = () => <Image src={moreVertical} alt="moreVertical" />;
export const Notification = () => <Image src={notification} alt="notification" />;
export const NotificationActive = () => <Image src={notificationActive} alt="notificationActive" />;
export const ArrowDown = () => <Image src={arrowDown} alt="arrowDown" />;
export const ArrowRight = () => <Image src={arrowRight} alt="arrowRight" />;
export const ArrowUp = () => <Image src={arrowUp} alt="arrowUp" />;
export const Aspect = () => <Image src={aspect} alt="aspect" />;
export const BookSaved = () => <Image src={bookSaved} alt="bookSaved" />;
export const Buildings2 = () => <Image src={buildings2} alt="buildings2" />;
export const Camera = () => <Image src={camera} alt="camera" />;
export const Car = () => <Image src={car} alt="car" />;
export const Clock = () => <Image src={clock} alt="clock" />;
export const CloseCircle = () => <Image src={closeCircle} alt="closeCircle" />;
export const DeleteBin = () => <Image src={deleteBin} alt="deleteBin" />;
export const Hashtag = () => <Image src={hashtag} alt="hashtag" />;
export const Location = () => <Image src={location} alt="location" />;
export const Map = () => <Image src={map} alt="map" />;
export const MenuBoard = () => <Image src={menuBoard} alt="menuBoard" />;
export const Navigation = () => <Image src={navigation} alt="navigation" />;
export const Note2 = () => <Image src={note2} alt="note2" />;
export const People = () => <Image src={people} alt="people" />;
export const Profile2user = () => <Image src={profile2user} alt="profile2user" />;
export const RestaurantTable = () => <Image src={restaurantTable} alt="restaurantTable" />;
export const Routing2 = () => <Image src={routing2} alt="routing2" />;
export const SearchNormal = () => <Image src={searchNormal} alt="searchNormal" />;
export const SecurityUser = () => <Image src={securityUser} alt="securityUser" />;
export const Send = () => <Image src={send} alt="send" />;
export const Share = () => <Image src={share} alt="share" />;
export const Share2 = () => <Image src={share2} alt="share2" />;
export const SmsTracking = () => <Image src={smsTracking} alt="smsTracking" />;
export const Squares = () => <Image src={squares} alt="squares" />;
export const TextalignJustifycenter = () => <Image src={textalignJustifycenter} alt="textalignJustifycenter" />;
export const TimerPause = () => <Image src={timerPause} alt="timerPause" />;
export const Trade = () => <Image src={trade} alt="trade" />;
export const Verify = () => <Image src={verify} alt="verify" />;
export const View360 = () => <Image src={view360} alt="view360" />;
export const Account1 = () => <Image src={account1} alt="account1" />;
export const Account2 = () => <Image src={account2} alt="account2" />;
export const Cart = () => <Image src={cart} alt="cart" />;
export const CartNumbers = () => <Image src={cartNumbers} alt="cartNumbers" />;
export const Like = () => <Image src={like} alt="like" />;
export const LikeDislike = () => <Image src={likeDislike} alt="likeDislike" />;
export const SettingsEq = () => <Image src={settingsEq} alt="settingsEq" />;
export const SettingsEqActive = () => <Image src={settingsEqActive} alt="settingsEqActive" />;
export const ShoppingBag = () => <Image src={shoppingBag} alt="shoppingBag" />;
export const ShoppingBagActive = () => <Image src={shoppingBagActive} alt="shoppingBagActive" />;
export const ViewFilterEnable = () => <Image src={viewFilterOff} alt="viewFilterOff" />;
export const ViewFilterDisable = () => <Image src={viewFilterOn} alt="viewFilterOn" />;
export const LocationAccent = () => <Image src={locationAccent} alt="locationAccent" />;
export const LocationAccentNumbers = () => <Image src={locationAccentNumbers} alt="locationAccentNumbers" />;
export const Mistake = () => <Image src={mistake} alt="mistake" />;
export const Successfully = () => <Image src={successfully} alt="successfully" />;
