import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'UI-Kit Demo',
	description: 'Generated by menualista'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={``}>{children}</body>
		</html>
	);
}
